# Generated by Django 3.2.9 on 2021-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_inheritence', '0002_auto_20211101_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('model_inheritence.person',),
        ),
    ]
